UniserGroupTask/UniserGroupTask/Controllers/AddressController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UniserGroupTask.Interfaces;
using UniserGroupTask.ViewModels;

namespace UniserGroupTask.Controllers
{
    [Authorize]
    public class AddressController : Controller
    {
        private readonly IUserService _userService;

        public AddressController(IUserService userService)
        {
            _userService = userService;
        }
        [HttpGet]
        public IActionResult Details(string id)
        {
            UserViewModel details = _userService.GetUserAddresses(id);
            return View(details);
        }
    }
}

UniserGroupTask/UniserGroupTask/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartSolutionTask.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UniserGroupTask.Interfaces;
using UniserGroupTask.ViewModels;

namespace UniserGroupTask.Controllers
{ 
    public class HomeController : Controller
    {
        private readonly IUserService _userService;

        public HomeController(IUserService userService)
        { 
            _userService = userService;
        }

        [Authorize(Roles = SystemRoles.UserRole)]
        public IActionResult Index()
        {
            UserViewModel userViewModel = _userService.GetAllUsers();
            return View(userViewModel);
        } 
    }
}

UniserGroupTask/UniserGroupTask/Views/Home/Index.cshtml
@model UserViewModel

    <div class="logout_block" style="">
        <form asp-controller="Account" asp-action="Logout" method="post">
            <a style="top: 0; position: relative" href="#" onclick="$(this).parents('form').submit()">
                <h4 class="logout_link" style="">Log Out</h4>
            </a>
        </form>
    </div>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">UserName</th>
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model?.AllUsers)
        {
            <tr>
                <td><a asp-controller="Address" asp-action="Details" asp-route-id="@user.Id"> @user.UserName</a></td>
                <td><a asp-controller="Address" asp-action="Details" asp-route-id="@user.Id"> @user.Name</a></td>
                <td><a asp-controller="Address" asp-action="Details" asp-route-id="@user.Id"> @user.Surname</a></td>
            </tr> 
        }

    </tbody>
</table>